name: Run scraper and publish plugins list as build artifact

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out GitHub repository
        uses: actions/checkout@v3
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
      - name: Build and run scraper
        run: |
          cd $GITHUB_WORKSPACE
          cargo run
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: plugins_list.json
          path: plugins.json
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
      - name: GitHub Release Action
        uses: ncipollo/release-action@v1
        with:
          artifacts: plugins.json
          name: ${{ steps.date.output.date }}
          body: "Plugins list scraped from getkirby.com on ${{ steps.date.output.date }}"
          tag: ${{ steps.date.output.date }}
          allowUpdates: true
          token: ${{ secrets.RELEASE_TOKEN }}
          
