name: Run scraper and publish plugins list as build artifact

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out GitHub repository
        uses: actions/checkout@v3
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
      - name: Build and run scraper
        run: |
          cd $GITHUB_WORKSPACE
          cargo run
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: plugins_list.json
          path: plugins.json
      - name: Create a Release
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_PATH: plugins.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

